// SPDX-License-Identifier: GPL-2.0-only

#include <linux/net/intel/libie.h>

/* Page Pool */

static u32 libie_rx_sync_len(const struct net_device *dev, u32 hr)
{
	u32 len;

	len = READ_ONCE(dev->mtu) + LIBIE_RX_LL_LEN;
	len = ALIGN(len, LIBIE_RX_BUF_LEN_ALIGN);
	len = min(len, LIBIE_RX_BUF_LEN(hr));

	return len;
}

struct page_pool *libie_rx_page_pool_create(const struct net_device *dev,
					    u32 size)
{
	u32 hr = LIBIE_SKB_HEADROOM;
	const struct page_pool_params pp = {
		.flags		= PP_FLAG_DMA_MAP | PP_FLAG_DMA_MAP_WEAK |
				  PP_FLAG_DMA_SYNC_DEV,
		.order		= LIBIE_RX_PAGE_ORDER,
		.pool_size	= size,
		.nid		= NUMA_NO_NODE,
		.dev		= dev->dev.parent,
		.dma_dir	= DMA_FROM_DEVICE,
		.max_len	= libie_rx_sync_len(dev, hr),
		.offset		= hr,
	};

	static_assert((PP_FLAG_DMA_MAP | PP_FLAG_DMA_MAP_WEAK) ==
		      LIBIE_RX_DMA_ATTR);

	return page_pool_create(&pp);
}
EXPORT_SYMBOL_NS_GPL(libie_rx_page_pool_create, LIBIE);

/* O(1) converting i40e/ice/iavf's 8/10-bit hardware packet type to a parsed
 * bitfield struct.
 */

#define LIBIE_PTT(pt, oip, oip_ver, ofrag, tun, teprot, tefrag, iprot, pl)    \
	[pt] = {							      \
		.outer_ip 		= LIBIE_RX_PTYPE_OUTER_##oip,	      \
		.outer_ip_ver		= LIBIE_RX_PTYPE_OUTER_##oip_ver,     \
		.outer_frag		= LIBIE_RX_PTYPE_##ofrag,	      \
		.tunnel_type		= LIBIE_RX_PTYPE_TUNNEL_IP_##tun,     \
		.tunnel_end_prot	= LIBIE_RX_PTYPE_TUNNEL_END_##teprot, \
		.tunnel_end_frag	= LIBIE_RX_PTYPE_##tefrag,	      \
		.inner_prot		= LIBIE_RX_PTYPE_INNER_PROT_##iprot,  \
		.payload_layer		= LIBIE_RX_PTYPE_PAYLOAD_LAYER_##pl,  \
	}

#define LIBIE_PTT_UNUSED_ENTRY(PTYPE)	[PTYPE] = { }

/* shorter macros makes the table fit but are terse */
#define LIBIE_RX_PTYPE_NOF		LIBIE_RX_PTYPE_NOT_FRAG
#define LIBIE_RX_PTYPE_FRG		LIBIE_RX_PTYPE_FRAG
#define LIBIE_RX_PTYPE_INNER_PROT_TS	LIBIE_RX_PTYPE_INNER_PROT_TIMESYNC

/* Lookup table mapping for O(1) parsing */
const struct libie_rx_ptype_parsed libie_rx_ptype_lut[LIBIE_RX_PTYPE_NUM] = {
	/* L2 Packet types */
	LIBIE_PTT_UNUSED_ENTRY(0),
	LIBIE_PTT(1,  L2, NONE, NOF, NONE, NONE, NOF, NONE, PAY2),
	LIBIE_PTT(2,  L2, NONE, NOF, NONE, NONE, NOF, TS,   PAY2),
	LIBIE_PTT(3,  L2, NONE, NOF, NONE, NONE, NOF, NONE, PAY2),
	LIBIE_PTT_UNUSED_ENTRY(4),
	LIBIE_PTT_UNUSED_ENTRY(5),
	LIBIE_PTT(6,  L2, NONE, NOF, NONE, NONE, NOF, NONE, PAY2),
	LIBIE_PTT(7,  L2, NONE, NOF, NONE, NONE, NOF, NONE, PAY2),
	LIBIE_PTT_UNUSED_ENTRY(8),
	LIBIE_PTT_UNUSED_ENTRY(9),
	LIBIE_PTT(10, L2, NONE, NOF, NONE, NONE, NOF, NONE, PAY2),
	LIBIE_PTT(11, L2, NONE, NOF, NONE, NONE, NOF, NONE, NONE),
	LIBIE_PTT(12, L2, NONE, NOF, NONE, NONE, NOF, NONE, PAY3),
	LIBIE_PTT(13, L2, NONE, NOF, NONE, NONE, NOF, NONE, PAY3),
	LIBIE_PTT(14, L2, NONE, NOF, NONE, NONE, NOF, NONE, PAY3),
	LIBIE_PTT(15, L2, NONE, NOF, NONE, NONE, NOF, NONE, PAY3),
	LIBIE_PTT(16, L2, NONE, NOF, NONE, NONE, NOF, NONE, PAY3),
	LIBIE_PTT(17, L2, NONE, NOF, NONE, NONE, NOF, NONE, PAY3),
	LIBIE_PTT(18, L2, NONE, NOF, NONE, NONE, NOF, NONE, PAY3),
	LIBIE_PTT(19, L2, NONE, NOF, NONE, NONE, NOF, NONE, PAY3),
	LIBIE_PTT(20, L2, NONE, NOF, NONE, NONE, NOF, NONE, PAY3),
	LIBIE_PTT(21, L2, NONE, NOF, NONE, NONE, NOF, NONE, PAY3),

	/* Non Tunneled IPv4 */
	LIBIE_PTT(22, IP, IPV4, FRG, NONE, NONE, NOF, NONE, PAY3),
	LIBIE_PTT(23, IP, IPV4, NOF, NONE, NONE, NOF, NONE, PAY3),
	LIBIE_PTT(24, IP, IPV4, NOF, NONE, NONE, NOF, UDP,  PAY4),
	LIBIE_PTT_UNUSED_ENTRY(25),
	LIBIE_PTT(26, IP, IPV4, NOF, NONE, NONE, NOF, TCP,  PAY4),
	LIBIE_PTT(27, IP, IPV4, NOF, NONE, NONE, NOF, SCTP, PAY4),
	LIBIE_PTT(28, IP, IPV4, NOF, NONE, NONE, NOF, ICMP, PAY4),

	/* IPv4 --> IPv4 */
	LIBIE_PTT(29, IP, IPV4, NOF, IP, IPV4, FRG, NONE, PAY3),
	LIBIE_PTT(30, IP, IPV4, NOF, IP, IPV4, NOF, NONE, PAY3),
	LIBIE_PTT(31, IP, IPV4, NOF, IP, IPV4, NOF, UDP,  PAY4),
	LIBIE_PTT_UNUSED_ENTRY(32),
	LIBIE_PTT(33, IP, IPV4, NOF, IP, IPV4, NOF, TCP,  PAY4),
	LIBIE_PTT(34, IP, IPV4, NOF, IP, IPV4, NOF, SCTP, PAY4),
	LIBIE_PTT(35, IP, IPV4, NOF, IP, IPV4, NOF, ICMP, PAY4),

	/* IPv4 --> IPv6 */
	LIBIE_PTT(36, IP, IPV4, NOF, IP, IPV6, FRG, NONE, PAY3),
	LIBIE_PTT(37, IP, IPV4, NOF, IP, IPV6, NOF, NONE, PAY3),
	LIBIE_PTT(38, IP, IPV4, NOF, IP, IPV6, NOF, UDP,  PAY4),
	LIBIE_PTT_UNUSED_ENTRY(39),
	LIBIE_PTT(40, IP, IPV4, NOF, IP, IPV6, NOF, TCP,  PAY4),
	LIBIE_PTT(41, IP, IPV4, NOF, IP, IPV6, NOF, SCTP, PAY4),
	LIBIE_PTT(42, IP, IPV4, NOF, IP, IPV6, NOF, ICMP, PAY4),

	/* IPv4 --> GRE/NAT */
	LIBIE_PTT(43, IP, IPV4, NOF, GRENAT, NONE, NOF, NONE, PAY3),

	/* IPv4 --> GRE/NAT --> IPv4 */
	LIBIE_PTT(44, IP, IPV4, NOF, GRENAT, IPV4, FRG, NONE, PAY3),
	LIBIE_PTT(45, IP, IPV4, NOF, GRENAT, IPV4, NOF, NONE, PAY3),
	LIBIE_PTT(46, IP, IPV4, NOF, GRENAT, IPV4, NOF, UDP,  PAY4),
	LIBIE_PTT_UNUSED_ENTRY(47),
	LIBIE_PTT(48, IP, IPV4, NOF, GRENAT, IPV4, NOF, TCP,  PAY4),
	LIBIE_PTT(49, IP, IPV4, NOF, GRENAT, IPV4, NOF, SCTP, PAY4),
	LIBIE_PTT(50, IP, IPV4, NOF, GRENAT, IPV4, NOF, ICMP, PAY4),

	/* IPv4 --> GRE/NAT --> IPv6 */
	LIBIE_PTT(51, IP, IPV4, NOF, GRENAT, IPV6, FRG, NONE, PAY3),
	LIBIE_PTT(52, IP, IPV4, NOF, GRENAT, IPV6, NOF, NONE, PAY3),
	LIBIE_PTT(53, IP, IPV4, NOF, GRENAT, IPV6, NOF, UDP,  PAY4),
	LIBIE_PTT_UNUSED_ENTRY(54),
	LIBIE_PTT(55, IP, IPV4, NOF, GRENAT, IPV6, NOF, TCP,  PAY4),
	LIBIE_PTT(56, IP, IPV4, NOF, GRENAT, IPV6, NOF, SCTP, PAY4),
	LIBIE_PTT(57, IP, IPV4, NOF, GRENAT, IPV6, NOF, ICMP, PAY4),

	/* IPv4 --> GRE/NAT --> MAC */
	LIBIE_PTT(58, IP, IPV4, NOF, GRENAT_MAC, NONE, NOF, NONE, PAY3),

	/* IPv4 --> GRE/NAT --> MAC --> IPv4 */
	LIBIE_PTT(59, IP, IPV4, NOF, GRENAT_MAC, IPV4, FRG, NONE, PAY3),
	LIBIE_PTT(60, IP, IPV4, NOF, GRENAT_MAC, IPV4, NOF, NONE, PAY3),
	LIBIE_PTT(61, IP, IPV4, NOF, GRENAT_MAC, IPV4, NOF, UDP,  PAY4),
	LIBIE_PTT_UNUSED_ENTRY(62),
	LIBIE_PTT(63, IP, IPV4, NOF, GRENAT_MAC, IPV4, NOF, TCP,  PAY4),
	LIBIE_PTT(64, IP, IPV4, NOF, GRENAT_MAC, IPV4, NOF, SCTP, PAY4),
	LIBIE_PTT(65, IP, IPV4, NOF, GRENAT_MAC, IPV4, NOF, ICMP, PAY4),

	/* IPv4 --> GRE/NAT -> MAC --> IPv6 */
	LIBIE_PTT(66, IP, IPV4, NOF, GRENAT_MAC, IPV6, FRG, NONE, PAY3),
	LIBIE_PTT(67, IP, IPV4, NOF, GRENAT_MAC, IPV6, NOF, NONE, PAY3),
	LIBIE_PTT(68, IP, IPV4, NOF, GRENAT_MAC, IPV6, NOF, UDP,  PAY4),
	LIBIE_PTT_UNUSED_ENTRY(69),
	LIBIE_PTT(70, IP, IPV4, NOF, GRENAT_MAC, IPV6, NOF, TCP,  PAY4),
	LIBIE_PTT(71, IP, IPV4, NOF, GRENAT_MAC, IPV6, NOF, SCTP, PAY4),
	LIBIE_PTT(72, IP, IPV4, NOF, GRENAT_MAC, IPV6, NOF, ICMP, PAY4),

	/* IPv4 --> GRE/NAT --> MAC/VLAN */
	LIBIE_PTT(73, IP, IPV4, NOF, GRENAT_MAC_VLAN, NONE, NOF, NONE, PAY3),

	/* IPv4 ---> GRE/NAT -> MAC/VLAN --> IPv4 */
	LIBIE_PTT(74, IP, IPV4, NOF, GRENAT_MAC_VLAN, IPV4, FRG, NONE, PAY3),
	LIBIE_PTT(75, IP, IPV4, NOF, GRENAT_MAC_VLAN, IPV4, NOF, NONE, PAY3),
	LIBIE_PTT(76, IP, IPV4, NOF, GRENAT_MAC_VLAN, IPV4, NOF, UDP,  PAY4),
	LIBIE_PTT_UNUSED_ENTRY(77),
	LIBIE_PTT(78, IP, IPV4, NOF, GRENAT_MAC_VLAN, IPV4, NOF, TCP,  PAY4),
	LIBIE_PTT(79, IP, IPV4, NOF, GRENAT_MAC_VLAN, IPV4, NOF, SCTP, PAY4),
	LIBIE_PTT(80, IP, IPV4, NOF, GRENAT_MAC_VLAN, IPV4, NOF, ICMP, PAY4),

	/* IPv4 -> GRE/NAT -> MAC/VLAN --> IPv6 */
	LIBIE_PTT(81, IP, IPV4, NOF, GRENAT_MAC_VLAN, IPV6, FRG, NONE, PAY3),
	LIBIE_PTT(82, IP, IPV4, NOF, GRENAT_MAC_VLAN, IPV6, NOF, NONE, PAY3),
	LIBIE_PTT(83, IP, IPV4, NOF, GRENAT_MAC_VLAN, IPV6, NOF, UDP,  PAY4),
	LIBIE_PTT_UNUSED_ENTRY(84),
	LIBIE_PTT(85, IP, IPV4, NOF, GRENAT_MAC_VLAN, IPV6, NOF, TCP,  PAY4),
	LIBIE_PTT(86, IP, IPV4, NOF, GRENAT_MAC_VLAN, IPV6, NOF, SCTP, PAY4),
	LIBIE_PTT(87, IP, IPV4, NOF, GRENAT_MAC_VLAN, IPV6, NOF, ICMP, PAY4),

	/* Non Tunneled IPv6 */
	LIBIE_PTT(88, IP, IPV6, FRG, NONE, NONE, NOF, NONE, PAY3),
	LIBIE_PTT(89, IP, IPV6, NOF, NONE, NONE, NOF, NONE, PAY3),
	LIBIE_PTT(90, IP, IPV6, NOF, NONE, NONE, NOF, UDP,  PAY4),
	LIBIE_PTT_UNUSED_ENTRY(91),
	LIBIE_PTT(92, IP, IPV6, NOF, NONE, NONE, NOF, TCP,  PAY4),
	LIBIE_PTT(93, IP, IPV6, NOF, NONE, NONE, NOF, SCTP, PAY4),
	LIBIE_PTT(94, IP, IPV6, NOF, NONE, NONE, NOF, ICMP, PAY4),

	/* IPv6 --> IPv4 */
	LIBIE_PTT(95,  IP, IPV6, NOF, IP, IPV4, FRG, NONE, PAY3),
	LIBIE_PTT(96,  IP, IPV6, NOF, IP, IPV4, NOF, NONE, PAY3),
	LIBIE_PTT(97,  IP, IPV6, NOF, IP, IPV4, NOF, UDP,  PAY4),
	LIBIE_PTT_UNUSED_ENTRY(98),
	LIBIE_PTT(99,  IP, IPV6, NOF, IP, IPV4, NOF, TCP,  PAY4),
	LIBIE_PTT(100, IP, IPV6, NOF, IP, IPV4, NOF, SCTP, PAY4),
	LIBIE_PTT(101, IP, IPV6, NOF, IP, IPV4, NOF, ICMP, PAY4),

	/* IPv6 --> IPv6 */
	LIBIE_PTT(102, IP, IPV6, NOF, IP, IPV6, FRG, NONE, PAY3),
	LIBIE_PTT(103, IP, IPV6, NOF, IP, IPV6, NOF, NONE, PAY3),
	LIBIE_PTT(104, IP, IPV6, NOF, IP, IPV6, NOF, UDP,  PAY4),
	LIBIE_PTT_UNUSED_ENTRY(105),
	LIBIE_PTT(106, IP, IPV6, NOF, IP, IPV6, NOF, TCP,  PAY4),
	LIBIE_PTT(107, IP, IPV6, NOF, IP, IPV6, NOF, SCTP, PAY4),
	LIBIE_PTT(108, IP, IPV6, NOF, IP, IPV6, NOF, ICMP, PAY4),

	/* IPv6 --> GRE/NAT */
	LIBIE_PTT(109, IP, IPV6, NOF, GRENAT, NONE, NOF, NONE, PAY3),

	/* IPv6 --> GRE/NAT -> IPv4 */
	LIBIE_PTT(110, IP, IPV6, NOF, GRENAT, IPV4, FRG, NONE, PAY3),
	LIBIE_PTT(111, IP, IPV6, NOF, GRENAT, IPV4, NOF, NONE, PAY3),
	LIBIE_PTT(112, IP, IPV6, NOF, GRENAT, IPV4, NOF, UDP,  PAY4),
	LIBIE_PTT_UNUSED_ENTRY(113),
	LIBIE_PTT(114, IP, IPV6, NOF, GRENAT, IPV4, NOF, TCP,  PAY4),
	LIBIE_PTT(115, IP, IPV6, NOF, GRENAT, IPV4, NOF, SCTP, PAY4),
	LIBIE_PTT(116, IP, IPV6, NOF, GRENAT, IPV4, NOF, ICMP, PAY4),

	/* IPv6 --> GRE/NAT -> IPv6 */
	LIBIE_PTT(117, IP, IPV6, NOF, GRENAT, IPV6, FRG, NONE, PAY3),
	LIBIE_PTT(118, IP, IPV6, NOF, GRENAT, IPV6, NOF, NONE, PAY3),
	LIBIE_PTT(119, IP, IPV6, NOF, GRENAT, IPV6, NOF, UDP,  PAY4),
	LIBIE_PTT_UNUSED_ENTRY(120),
	LIBIE_PTT(121, IP, IPV6, NOF, GRENAT, IPV6, NOF, TCP,  PAY4),
	LIBIE_PTT(122, IP, IPV6, NOF, GRENAT, IPV6, NOF, SCTP, PAY4),
	LIBIE_PTT(123, IP, IPV6, NOF, GRENAT, IPV6, NOF, ICMP, PAY4),

	/* IPv6 --> GRE/NAT -> MAC */
	LIBIE_PTT(124, IP, IPV6, NOF, GRENAT_MAC, NONE, NOF, NONE, PAY3),

	/* IPv6 --> GRE/NAT -> MAC -> IPv4 */
	LIBIE_PTT(125, IP, IPV6, NOF, GRENAT_MAC, IPV4, FRG, NONE, PAY3),
	LIBIE_PTT(126, IP, IPV6, NOF, GRENAT_MAC, IPV4, NOF, NONE, PAY3),
	LIBIE_PTT(127, IP, IPV6, NOF, GRENAT_MAC, IPV4, NOF, UDP,  PAY4),
	LIBIE_PTT_UNUSED_ENTRY(128),
	LIBIE_PTT(129, IP, IPV6, NOF, GRENAT_MAC, IPV4, NOF, TCP,  PAY4),
	LIBIE_PTT(130, IP, IPV6, NOF, GRENAT_MAC, IPV4, NOF, SCTP, PAY4),
	LIBIE_PTT(131, IP, IPV6, NOF, GRENAT_MAC, IPV4, NOF, ICMP, PAY4),

	/* IPv6 --> GRE/NAT -> MAC -> IPv6 */
	LIBIE_PTT(132, IP, IPV6, NOF, GRENAT_MAC, IPV6, FRG, NONE, PAY3),
	LIBIE_PTT(133, IP, IPV6, NOF, GRENAT_MAC, IPV6, NOF, NONE, PAY3),
	LIBIE_PTT(134, IP, IPV6, NOF, GRENAT_MAC, IPV6, NOF, UDP,  PAY4),
	LIBIE_PTT_UNUSED_ENTRY(135),
	LIBIE_PTT(136, IP, IPV6, NOF, GRENAT_MAC, IPV6, NOF, TCP,  PAY4),
	LIBIE_PTT(137, IP, IPV6, NOF, GRENAT_MAC, IPV6, NOF, SCTP, PAY4),
	LIBIE_PTT(138, IP, IPV6, NOF, GRENAT_MAC, IPV6, NOF, ICMP, PAY4),

	/* IPv6 --> GRE/NAT -> MAC/VLAN */
	LIBIE_PTT(139, IP, IPV6, NOF, GRENAT_MAC_VLAN, NONE, NOF, NONE, PAY3),

	/* IPv6 --> GRE/NAT -> MAC/VLAN --> IPv4 */
	LIBIE_PTT(140, IP, IPV6, NOF, GRENAT_MAC_VLAN, IPV4, FRG, NONE, PAY3),
	LIBIE_PTT(141, IP, IPV6, NOF, GRENAT_MAC_VLAN, IPV4, NOF, NONE, PAY3),
	LIBIE_PTT(142, IP, IPV6, NOF, GRENAT_MAC_VLAN, IPV4, NOF, UDP,  PAY4),
	LIBIE_PTT_UNUSED_ENTRY(143),
	LIBIE_PTT(144, IP, IPV6, NOF, GRENAT_MAC_VLAN, IPV4, NOF, TCP,  PAY4),
	LIBIE_PTT(145, IP, IPV6, NOF, GRENAT_MAC_VLAN, IPV4, NOF, SCTP, PAY4),
	LIBIE_PTT(146, IP, IPV6, NOF, GRENAT_MAC_VLAN, IPV4, NOF, ICMP, PAY4),

	/* IPv6 --> GRE/NAT -> MAC/VLAN --> IPv6 */
	LIBIE_PTT(147, IP, IPV6, NOF, GRENAT_MAC_VLAN, IPV6, FRG, NONE, PAY3),
	LIBIE_PTT(148, IP, IPV6, NOF, GRENAT_MAC_VLAN, IPV6, NOF, NONE, PAY3),
	LIBIE_PTT(149, IP, IPV6, NOF, GRENAT_MAC_VLAN, IPV6, NOF, UDP,  PAY4),
	LIBIE_PTT_UNUSED_ENTRY(150),
	LIBIE_PTT(151, IP, IPV6, NOF, GRENAT_MAC_VLAN, IPV6, NOF, TCP,  PAY4),
	LIBIE_PTT(152, IP, IPV6, NOF, GRENAT_MAC_VLAN, IPV6, NOF, SCTP, PAY4),
	LIBIE_PTT(153, IP, IPV6, NOF, GRENAT_MAC_VLAN, IPV6, NOF, ICMP, PAY4),
};
EXPORT_SYMBOL_NS_GPL(libie_rx_ptype_lut, LIBIE);

MODULE_AUTHOR("Intel Corporation");
MODULE_DESCRIPTION("Intel(R) Ethernet common library");
MODULE_LICENSE("GPL");
