# SPDX-License-Identifier: GPL-2.0-only
# Copyright(c) 2023 Intel Corporation.

obj-$(CONFIG_LIBIE)	+= libie.o

libie-objs		+= rx.o
libie-objs		+= stats.o
libie-objs		+= tx.o
libie-objs		+= xdp.o
libie-objs		+= xsk.o
